package N4FR_Methods;



/*
 * misFractales.java
 *
 */

import javax.swing.JOptionPane;
import java.awt.Graphics;




public class n4FR extends javax.swing.JFrame {
    private int nRec;
    private N4FR_Fractal miFractal;
    private N4FR_Koch miKoch;
    private N4FR_Dragon miDragon;
    private N4FR_CurvaHilbert micurvH;
    private N4FR_Sierpinski miSier;
    private N4FR_Albenson miAlb;
    private N4FR_Gosper miGasparin;
    private N4FR_Square miSquartle;
    private N4FR_Poligon mipoligon;
    private N4FR_Weave miOla;
    private N4FR_Triangulos minido;
    private N4FR_Snow miSnow;
    
    /** Creates new form misFractales */
    public n4FR() {
        this.setTitle("Fractales");
        nRec = 3;
        initComponents();
        
        //declaracion de objetos (Fractales)
        miKoch = new N4FR_Koch(nRec, 20.0, jPanelFractales);
        miKoch.posicion(-10.0, 0.0);
        miDragon = new N4FR_Dragon(nRec, 20.0, jPanelFractales);
        miDragon.posicion(0.0, 0.0);
        micurvH= new N4FR_CurvaHilbert(nRec, 20.0, jPanelFractales);
        micurvH.posicion(-20.0, -5.0);
        miSier= new N4FR_Sierpinski (nRec, 20.0, jPanelFractales);
        miSier.posicion(-25.0, 15.0);
        miAlb = new N4FR_Albenson(nRec, 20.0, jPanelFractales);
        miAlb.posicion(10.0, 0.0);
        miGasparin = new N4FR_Gosper(nRec, 20.0, jPanelFractales);
        miGasparin.posicion(-20.0, 0.0);
        miSquartle = new N4FR_Square(nRec, 20.0, jPanelFractales);
        miSquartle.posicion(-20.0, 10.0);
        mipoligon = new N4FR_Poligon(nRec, 20.0, jPanelFractales);
        mipoligon.posicion(-10.0, 0.0);
        miOla = new N4FR_Weave(nRec, 20.0, jPanelFractales);
        miOla.posicion(-10.0, 0.0);
        minido = new N4FR_Triangulos(nRec, 20.0, jPanelFractales);
        minido.posicion(-10.0, 0.0);
        miSnow = new N4FR_Snow(nRec, 20.0, jPanelFractales);
        miSnow.posicion(-10.0, 0.0);
        
       
        
        //Fin de la declaracion
        miFractal = null;
        jSpinnerNivelRecursion.getModel().setValue(nRec);
        jSpinnerNivelRecursion.setEnabled(false);
    }

    public void paint(Graphics g){
        this.paintComponents(g);
        if (miFractal != null){
            miFractal.reinicia();
            miFractal.asignaNivelRecursion(nRec);
            miFractal.dibuja();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFractales = new javax.swing.JPanel();
        jLabelNivelRecursion = new javax.swing.JLabel();
        jSpinnerNivelRecursion = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemKoch = new javax.swing.JMenuItem();
        jMenuItemDragon = new javax.swing.JMenuItem();
        jMenuItemCurvH = new javax.swing.JMenuItem();
        jMenuItemCurvSierpins = new javax.swing.JMenuItem();
        jMenuItemAlbenson = new javax.swing.JMenuItem();
        jMenuItemSquare = new javax.swing.JMenuItem();
        jMenuItemAbCornPol = new javax.swing.JMenuItem();
        jMenuItemWave = new javax.swing.JMenuItem();
        jMenuItemTriangulos = new javax.swing.JMenuItem();
        jMenuItemMaze = new javax.swing.JMenuItem();
        jMenuItemGosper = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAcercaDe = new javax.swing.JMenu();
        jMenuItemPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanelFractales.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lienzo para los fractales"));

        jLabelNivelRecursion.setText("Nivel de recursión:");

        jSpinnerNivelRecursion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerNivelRecursionStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelFractalesLayout = new javax.swing.GroupLayout(jPanelFractales);
        jPanelFractales.setLayout(jPanelFractalesLayout);
        jPanelFractalesLayout.setHorizontalGroup(
            jPanelFractalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFractalesLayout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(jLabelNivelRecursion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerNivelRecursion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFractalesLayout.setVerticalGroup(
            jPanelFractalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFractalesLayout.createSequentialGroup()
                .addGroup(jPanelFractalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerNivelRecursion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNivelRecursion))
                .addContainerGap(346, Short.MAX_VALUE))
        );

        jMenuOpciones.setText("Opciones");

        jMenuItemKoch.setText("Koch");
        jMenuItemKoch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKochActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemKoch);

        jMenuItemDragon.setText("Dragon");
        jMenuItemDragon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDragonActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemDragon);

        jMenuItemCurvH.setText("Curv. Hilbert");
        jMenuItemCurvH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCurvHActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemCurvH);

        jMenuItemCurvSierpins.setText("Curv. Sierpinski");
        jMenuItemCurvSierpins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCurvSierpinsActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemCurvSierpins);

        jMenuItemAlbenson.setText("Abelson C. Curv.");
        jMenuItemAlbenson.setToolTipText("");
        jMenuItemAlbenson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlbensonActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemAlbenson);

        jMenuItemSquare.setText("Cuad. of Mandelbrot");
        jMenuItemSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSquareActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSquare);

        jMenuItemAbCornPol.setText("Abelson Cor. Pol.");
        jMenuItemAbCornPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbCornPolActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemAbCornPol);

        jMenuItemWave.setText("Malmberg Weave");
        jMenuItemWave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWaveActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemWave);

        jMenuItemTriangulos.setText("Triangles");
        jMenuItemTriangulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTriangulosActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemTriangulos);

        jMenuItemMaze.setText("Mandelbrot H. Snowflake");
        jMenuItemMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMazeActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemMaze);

        jMenuItemGosper.setText("Gosper Curve");
        jMenuItemGosper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGosperActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemGosper);
        jMenuOpciones.add(jSeparator1);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSalir);

        jMenuBar1.add(jMenuOpciones);

        jMenuAcercaDe.setText("acerca de ...");

        jMenuItemPrograma.setText("este programa");
        jMenuItemPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProgramaActionPerformed(evt);
            }
        });
        jMenuAcercaDe.add(jMenuItemPrograma);

        jMenuBar1.add(jMenuAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFractales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFractales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerNivelRecursionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerNivelRecursionStateChanged
// TODO add your handling code here:
        nRec = (Integer)(jSpinnerNivelRecursion.getModel().getValue());
        if (nRec<0 || nRec>10) {
            nRec = nRec<0?0:10;
            jSpinnerNivelRecursion.getModel().setValue(nRec);
            return;
        }
        repaint();
    }//GEN-LAST:event_jSpinnerNivelRecursionStateChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
// TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_formComponentResized

    private void jMenuItemKochActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKochActionPerformed
// TODO add your handling code here:
        miFractal = miKoch;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemKochActionPerformed

    private void xSalir(){
        int resp=JOptionPane.showConfirmDialog(this, "Por terminar el programa",
                "Aviso", JOptionPane.OK_CANCEL_OPTION);
        if (resp == JOptionPane.OK_OPTION) System.exit(0);
    }
    
    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
// TODO add your handling code here:
        xSalir();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProgramaActionPerformed
      // TODO add your handling code here:
      JOptionPane.showMessageDialog(null, "\nPrograma Realizado por:\n Victor Hugo Martinez \n inspirado en las ideas de: Carlos Coronado",
        "Acerca de ...", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jMenuItemProgramaActionPerformed

    private void jMenuItemDragonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDragonActionPerformed
        // TODO add your handling code here:
        miFractal = miDragon;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemDragonActionPerformed

    private void jMenuItemCurvHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCurvHActionPerformed
        // TODO add your handling code here:
        miFractal = micurvH;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemCurvHActionPerformed

    private void jMenuItemCurvSierpinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCurvSierpinsActionPerformed
        // TODO add your handling code here:
        miFractal = miSier;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemCurvSierpinsActionPerformed

    private void jMenuItemAlbensonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlbensonActionPerformed
        // TODO add your handling code here:
        miFractal = miAlb;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemAlbensonActionPerformed

    private void jMenuItemGosperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGosperActionPerformed
        // TODO add your handling code here:
        miFractal = miGasparin;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemGosperActionPerformed

    private void jMenuItemSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSquareActionPerformed
        // TODO add your handling code here:
        miFractal = miSquartle;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemSquareActionPerformed

    private void jMenuItemAbCornPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbCornPolActionPerformed
        // TODO add your handling code here:
        miFractal = mipoligon;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemAbCornPolActionPerformed

    private void jMenuItemWaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWaveActionPerformed
        // TODO add your handling code here:
        miFractal = miOla;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemWaveActionPerformed

    private void jMenuItemTriangulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTriangulosActionPerformed
        // TODO add your handling code here:
        miFractal = minido;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemTriangulosActionPerformed

    private void jMenuItemMazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMazeActionPerformed
        // TODO add your handling code here:
         miFractal = miSnow;
        jSpinnerNivelRecursion.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jMenuItemMazeActionPerformed
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new n4FR().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNivelRecursion;
    private javax.swing.JMenu jMenuAcercaDe;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbCornPol;
    private javax.swing.JMenuItem jMenuItemAlbenson;
    private javax.swing.JMenuItem jMenuItemCurvH;
    private javax.swing.JMenuItem jMenuItemCurvSierpins;
    private javax.swing.JMenuItem jMenuItemDragon;
    private javax.swing.JMenuItem jMenuItemGosper;
    private javax.swing.JMenuItem jMenuItemKoch;
    private javax.swing.JMenuItem jMenuItemMaze;
    private javax.swing.JMenuItem jMenuItemPrograma;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemSquare;
    private javax.swing.JMenuItem jMenuItemTriangulos;
    private javax.swing.JMenuItem jMenuItemWave;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JPanel jPanelFractales;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerNivelRecursion;
    // End of variables declaration//GEN-END:variables
    
}
